;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_set_vram_addr
	.import		_copy_to_vram
	.export		_pal
	.export		_set_palette
	.export		_main

.segment	"DATA"

_pal:
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F

; ---------------------------------------------------------------
; void __near__ set_palette (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_palette: near

.segment	"CODE"

	jsr     pushax
	ldx     #$3F
	lda     #$00
	jsr     _set_vram_addr
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	ldx     #$00
	lda     #$10
	jsr     _copy_to_vram
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(_pal)
	ldx     #>(_pal)
	jsr     _set_palette
L002F:	jmp     L002F

.endproc

